server:
  port: 8081
  servlet:
    context-path: /api
  tomcat:
    max-connections: 30

spring:
  application:
    name: demo-local

  cloud:
    gcp:
      core:
        enabled: false
      logging:
        enabled: false
      metrics:
        enabled: false
      trace:
        enabled: false
      secretmanager:
        enabled: false

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    hikari:
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      minimum-idle: 1
      maximum-pool-size: 10
  liquibase:
    change-log: classpath:/db/changelog/db-changelog-master.yaml


management:
  stackdriver:
    metrics:
      export:
        enabled: false
  server:
    port: 8088
  endpoints:
    web:
      base-path: /metrics
      exposure:
        include: health