--liquibase formatted sql

--changeset DEMO:1
CREATE SCHEMA "demo";

CREATE TABLE "demo"."tech" (
  "seq_no" INT GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(20)
);

INSERT INTO demo.tech (name) VALUES
    ('Java'),
    ('Python');
